git clone https://github.com/tensorflow/adanet.git
git clone https://github.com/tensorflow/addons.git
git clone https://github.com/tensorflow/agents.git
git clone https://github.com/tensorflow/autograph.git
git clone https://github.com/tensorflow/benchmarks.git
git clone https://github.com/tensorflow/build.git
git clone https://github.com/tensorflow/cleverhans.git
git clone https://github.com/tensorflow/cloud.git
git clone https://github.com/tensorflow/community.git
git clone https://github.com/tensorflow/compression.git
git clone https://github.com/tensorflow/custom-op.git
git clone https://github.com/tensorflow/data-validation.git
git clone https://github.com/tensorflow/datasets.git
git clone https://github.com/tensorflow/deepmath.git
git clone https://github.com/tensorflow/docs.git
git clone https://github.com/tensorflow/docs-l10n.git
git clone https://github.com/tensorflow/ecosystem.git
git clone https://github.com/tensorflow/embedding-projector-standalone.git
git clone https://github.com/tensorflow/estimator.git
git clone https://github.com/tensorflow/examples.git
git clone https://github.com/tensorflow/fairness-indicators.git
git clone https://github.com/tensorflow/federated.git
git clone https://github.com/tensorflow/fold.git
git clone https://github.com/tensorflow/gan.git
git clone https://github.com/tensorflow/graphics.git
git clone https://github.com/tensorflow/haskell.git
git clone https://github.com/tensorflow/hub.git
git clone https://github.com/tensorflow/io.git
git clone https://github.com/tensorflow/java.git
git clone https://github.com/tensorflow/java-models.git
git clone https://github.com/tensorflow/kfac.git
git clone https://github.com/tensorflow/lattice.git
git clone https://github.com/tensorflow/lingvo.git
git clone https://github.com/tensorflow/lucid.git
git clone https://github.com/tensorflow/mesh.git
git clone https://github.com/tensorflow/metadata.git
git clone https://github.com/tensorflow/minigo.git
git clone https://github.com/tensorflow/mlir.git
git clone https://github.com/tensorflow/mlir-hlo.git
git clone https://github.com/tensorflow/model-analysis.git
git clone https://github.com/tensorflow/model-card-toolkit.git
git clone https://github.com/tensorflow/model-optimization.git
git clone https://github.com/tensorflow/models.git
git clone https://github.com/tensorflow/moonlight.git
git clone https://github.com/tensorflow/networking.git
git clone https://github.com/tensorflow/neural-structured-learning.git
git clone https://github.com/tensorflow/ngraph-bridge.git
git clone https://github.com/tensorflow/nmt.git
git clone https://github.com/tensorflow/playground.git
git clone https://github.com/tensorflow/privacy.git
git clone https://github.com/tensorflow/probability.git
git clone https://github.com/tensorflow/profiler.git
git clone https://github.com/tensorflow/profiler-ui.git
git clone https://github.com/tensorflow/quantum.git
git clone https://github.com/tensorflow/ranking.git
git clone https://github.com/tensorflow/recommenders.git
git clone https://github.com/tensorflow/runtime.git
git clone https://github.com/tensorflow/rust.git
git clone https://github.com/tensorflow/serving.git
git clone https://github.com/tensorflow/skflow.git
git clone https://github.com/tensorflow/swift.git
git clone https://github.com/tensorflow/swift-apis.git
git clone https://github.com/tensorflow/swift-bindings.git
git clone https://github.com/tensorflow/swift-models.git
git clone https://github.com/tensorflow/tcav.git
git clone https://github.com/tensorflow/tensor2tensor.git
git clone https://github.com/tensorflow/tensorboard.git
git clone https://github.com/tensorflow/tensorboard-plugin-example.git
git clone https://github.com/tensorflow/tensorflow.git
git clone https://github.com/tensorflow/tensorrt.git
git clone https://github.com/tensorflow/tensorstore.git
git clone https://github.com/tensorflow/text.git
git clone https://github.com/tensorflow/tfhub.dev.git
git clone https://github.com/tensorflow/tfjs.git
git clone https://github.com/tensorflow/tfjs-converter.git
git clone https://github.com/tensorflow/tfjs-core.git
git clone https://github.com/tensorflow/tfjs-data.git
git clone https://github.com/tensorflow/tfjs-examples.git
git clone https://github.com/tensorflow/tfjs-layers.git
git clone https://github.com/tensorflow/tfjs-models.git
git clone https://github.com/tensorflow/tfjs-node.git
git clone https://github.com/tensorflow/tfjs-tsne.git
git clone https://github.com/tensorflow/tfjs-vis.git
git clone https://github.com/tensorflow/tfjs-website.git
git clone https://github.com/tensorflow/tfjs-wechat.git
git clone https://github.com/tensorflow/tflite-support.git
git clone https://github.com/tensorflow/tfrc.git
git clone https://github.com/tensorflow/tfx.git
git clone https://github.com/tensorflow/tfx-bsl.git
git clone https://github.com/tensorflow/toolchains.git
git clone https://github.com/tensorflow/tpu.git
git clone https://github.com/tensorflow/transform.git
git clone https://github.com/tensorflow/workshops.git
